name: dump_and_drop
description: "A logistics and delivery app for drivers and customers."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  google_sign_in: ^6.3.0
  firebase_storage: ^12.2.2
  firebase_messaging: ^15.1.3
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.3
  get: ^4.6.5
  url_launcher: ^6.1.10

  http: ^1.2.1
  dio: ^5.4.3+1

  flutter_map: ^7.0.0
  latlong2: ^0.9.0
  image_picker: ^1.0.4
  
  google_maps_flutter: ^2.5.1
  geolocator: ^11.0.0
  
  smooth_page_indicator: ^1.1.0
  intl: ^0.19.0
  
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  
  riverpod_generator: ^2.4.2
  build_runner: ^2.4.12

flutter:
  uses-material-design: true

  assets:
    - assets/images/spalsh_screen_logo.png
    - assets/images/logo.jpg
    - assets/images/home.jpg
    - assets/images/home_logo.jpg
    - assets/images/signup.png
    - assets/images/login.png
    - assets/images/car.png
  
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
